# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: business_api_development
  username: business_user
  password: business_password
  host: postgres
  port: 5432

test:
  <<: *default
  database: business_api_test
  username: business_user
  password: business_password
  host: postgres
  port: 5432

production:
  <<: *default
  database: business_api_production
  username: business_user
  password: business_password
  host: postgres
  port: 5432