validation_messages:
  # === 基本バリデーションメッセージ ===
  presence: "は必須です"
  blank: "を入力してください"

  # === フォーマット系メッセージ ===
  japanese_name: "に使用できない文字が含まれています（ひらがな・カタカナ・漢字・英数字・ハイフン・スペースのみ）"
  japanese_address: "に使用できない文字が含まれています（住所として正しい文字のみ）"
  katakana: "はカタカナのみ使用できます"
  hiragana: "はひらがなのみ使用できます"

  # === 連絡先系メッセージ ===
  email: "の形式が正しくありません（例：user@example.com）"
  phone: "の形式が正しくありません（例：03-1234-5678）"
  mobile_phone: "の形式が正しくありません（例：090-1234-5678）"
  postal_code: "の形式が正しくありません（例：123-4567）"

  # === 識別子系メッセージ ===
  alphanumeric: "は英数字のみ使用できます"
  username: "は英数字・ハイフン・アンダースコアのみ使用できます"
  alpha: "は英字のみ使用できます"
  numeric: "は数字のみ使用できます"

  # === URL・ウェブ系メッセージ ===
  url: "の形式が正しくありません（例：https://example.com）"
  domain: "の形式が正しくありません（例：example.com）"

  # === 金融系メッセージ ===
  credit_card: "の形式が正しくありません（例：1234-5678-9012-3456）"
  bank_account: "の形式が正しくありません（7桁の数字で入力してください）"

  # === パスワード系メッセージ ===
  strong_password: "は英大文字・英小文字・数字・記号をそれぞれ含む8文字以上で設定してください"
  medium_password: "は英数字8文字以上で設定してください"

  # === 長さ系メッセージ ===
  too_long: "は%{count}文字以内で入力してください"
  too_short: "は%{count}文字以上で入力してください"
  wrong_length: "は%{count}文字で入力してください"

  # === 数値系メッセージ ===
  not_a_number: "は数値で入力してください"
  greater_than: "は%{count}より大きい値を入力してください"
  greater_than_or_equal_to: "は%{count}以上の値を入力してください"
  less_than: "は%{count}より小さい値を入力してください"
  less_than_or_equal_to: "は%{count}以下の値を入力してください"

  # === 一意性・関連性メッセージ ===
  taken: "は既に使用されています"
  invalid: "が正しくありません"
  confirmation: "と%{attribute}が一致しません"
  accepted: "を受諾してください"