# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: business_api_postgres
    environment:
      POSTGRES_DB: business_api_development
      POSTGRES_USER: business_user
      POSTGRES_PASSWORD: business_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: business_api_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: business_api_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  app:
    build: .
    container_name: portfolio_office_app
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://business_user:business_password@postgres:5432/business_api_development
    command: bundle exec rails server -b 0.0.0.0 -p 3001

volumes:
  postgres_data:
  bundle_cache:
  pgadmin_data: