validation_messages:
  presence: " is required"
  blank: " cannot be blank"
  japanese_name: " contains invalid characters (Japanese characters, alphanumeric, hyphen, space only)"
  japanese_address: " contains invalid characters (valid address characters only)"
  katakana: " must be Katakana only"
  hiragana: " must be Hiragana only"
  email: " format is invalid (example: user@example.com)"
  phone: " format is invalid (example: 03-1234-5678)"
  mobile_phone: " format is invalid (example: 090-1234-5678)"
  postal_code: " format is invalid (example: 123-4567)"
  alphanumeric: " must be alphanumeric only"
  username: " must be alphanumeric, hyphen, or underscore only"
  alpha: " must be alphabetic only"
  numeric: " must be numeric only"
  url: " format is invalid (example: https://example.com)"
  domain: " format is invalid (example: example.com)"
  credit_card: " format is invalid (example: 1234-5678-9012-3456)"
  bank_account: " format is invalid (7 digits required)"
  strong_password: " must contain uppercase, lowercase, numbers, and symbols (8+ characters)"
  medium_password: " must be alphanumeric (8+ characters)"
  too_long: " is too long (maximum is %{count} characters)"
  too_short: " is too short (minimum is %{count} characters)"
  wrong_length: " must be exactly %{count} characters"
  not_a_number: " must be a number"
  greater_than: " must be greater than %{count}"
  greater_than_or_equal_to: " must be greater than or equal to %{count}"
  less_than: " must be less than %{count}"
  less_than_or_equal_to: " must be less than or equal to %{count}"
  taken: " has already been taken"
  invalid: " is invalid"
  confirmation: " doesn't match %{attribute}"
  accepted: " must be accepted"